class EBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{
	Default
	{
		Health 20;
		Radius 10;
		Height 42;
		+SOLID
		+SHOOTABLE
		+NOBLOOD
		+ACTIVATEMCROSS
		+DONTGIB
		+NOICEDEATH
		+OLDRADIUSDMG
		DeathSound "world/barrelx";
		Obituary "$OB_BARREL";
	}
	States
	{
	Spawn:
		BAR0 ABCDE random(3,5);
		Loop;
	Death:
		bexp AB 5 Bright;
		bexp C 3 Bright;
		bexp D 1 Bright A_Scream;

		TNT1 A 0 a_quake (2,3,0,600,0);
		TNT1 A 0 a_quake (1,7,0,1000,0);

	goto finish;
		
	finish:
		bexp D 1 Bright;
		bexp E 2 Bright A_Explode();
		bexp FGH 3 Bright;
		bexp I 3 Bright;
		bexp I 1050 Bright A_BarrelDestroy;
		bexp I 5 A_Respawn;
	}		
	// Death:
	// 	BEXP A 3;
	// 	BEXP B 3;
	// 	BEXP C 3 BRIGHT A_Scream;
	// 	expl A 4 BRIGHT;
	// 	expl B 4 BRIGHT;
	// 	expl C 4 BRIGHT;
	// 	expl D 4 BRIGHT A_Explode();
	// 	expl E 4 BRIGHT;
	// 	expl F 4 BRIGHT;
	// 	TNT1 A 1050 A_BarrelDestroy;
	// 	TNT1 A 5 {
	// 	A_SetRenderstyle(1.0,Style_Normal);
	// 	A_Respawn();
	// 	A_RemoveChildren(true,RMVF_EVERYTHING);
	// 	}
	// 	Wait;
	// }

	// Death:
	// 	TNT1 A 0 { 
	// 		A_RemoveChildren(1,RMVF_EVERYTHING);
	// 		A_StopSound(4);
	// 		A_SetRenderStyle(0.5,STYLE_Add);
	// 		A_SetRoll(random(0,359));
	// 		A_Explode();
	// 		}
	// 	expl ABCDEF 3 bright;
	// 	stop;
}