//Tracing projectiles goes here

class Tracer : FastProjectile
// Actor Tracer: FastProjectile
{
    Default
	{
    Projectile;
    +RANDOMIZE
    +FORCEXYBILLBOARD
    +DONTSPLASH
    // +BLOODSPLATTER 
    +NOEXTREMEDEATH
    damage 0;
    radius 2;
    height 2;
    speed 140;
    renderstyle "Add";
    alpha 0.9;
    scale 0.15;
    }
states
	{
	Spawn:
        TRAC A 1 BRIGHT;
        Loop;
    Death:
        Stop;
    XDeath:
        TNT1 A 0;
        Stop;
	}
}