// --------------------------------------------------------------------------
//
// Melee Weapons
//
// --------------------------------------------------------------------------

const PistolOverlay = 50;
Class Melee_Attacks : BEweapon Replaces Fist
{
	
	Default
	{
	Weapon.SelectionOrder 11;
	Weapon.Kickback 100;
	Obituary "%o was Ripped and Teared by 	%k";
	+WEAPON.WIMPY_WEAPON;
	+WEAPON.MELEEWEAPON;
    +WEAPON.NOALERT;
    +WEAPON.NOAUTOAIM;
	+WEAPON.CHEATNOTWEAPON;
	}
	States
	{

	Reload:
	TNT1 A 0 A_jumpifinventory("PowerStrength",1,"SelectFatalityModes");
	    PUNS BCD 1;
		PUNS E 7 A_PlaySound("Knuckled");
		PUNS FGFE 3;
		PUNS DCB 1 A_TakeInventory("Reloading", 1);
		Goto Ready+8;

	SelectFatalityModes:
	    TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("NoFatality", 1, "FatalityOn");
		Goto FatalityOff;
	FatalityOn:
	    TNT1 A 0 A_Print("RIP AND TEAR! Mode");
	    PUNS BCD 1;
		PUNS E 7 A_PlaySound("Knuckled");
		PUNS FGFE 3 A_TakeInventory("Reloading", 1);
		PUNS DCB 1 A_TakeInventory("NoFatality", 1);
		Goto Ready+9;

	FatalityOff:
		TNT1 A 0 A_Print("SMASH Mode");
	    PUNS BCD 1;
		PUNS E 7 A_PlaySound("Knuckled");
		PUNS FGFE 3 A_TakeInventory("Reloading", 1);
		PUNS DCB 1 A_GiveInventory("NoFatality", 1);
		Goto Ready+9;
	DoingFatality:
	PUNG A 1;
	TNT1 A 0 ACS_Execute(477, 0, 0, 0, 0);
	Goto Ready+9;


	Ready:
		TNT1 A 0 A_ZoomFactor(1.0);
	//	TNT1 A 0 A_JumpIfInventory("RifleWasEmpty", 1, "LoadChamber");
        PUNS ABCDCBA 1;
	ReallyReady:
	ReadyCont:
		TNT1 A 0 A_ZoomFactor(1.0);
        ////////////////// Check if player is performing a fatality\\\\;
		TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"ReadySoul");
        TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
        ////////////////////;
        TNT1 AAA 0;
		TNT1 A 0 A_JumpIfInventory("ShotgunguyHead",1,"ReadyShotgunguyHead");
        TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
		TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"ReadyBarrel");
        TNT1 A 0 A_JumpIfInventory("Kicking",1,"DoKick");
    //    TNT1 A 0 A_JumpIfInventory("Taunting",1,"Taunt");
	//	TNT1 A 0 A_JumpIfInventory("Reloading",1,"Reload");
        PUNG A 1 A_WeaponReady(WRF_ALLOWRELOAD);
		TNT1 A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade");
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFire");
		TNT1 A 0 A_GunFlash;
		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		Loop;
	ReadySoul:
		TNT1 A 0 A_JumpIf(CountInv("PowerStrength") == 0,"KillLS");
        TNT1 A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		TNT1 A 0 A_JumpIfInventory("Reloading",1,"KillLS");
	//	THEA A 7 BRIGHT A_WeaponReady(WRF_NOFIRE);
        THEA A 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA B 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA A 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA B 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA C 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA D 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA C 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
        THEA D 7 BRIGHT A_WeaponReady;
        TNT1 A 0 A_FireProjectile("LostSoulOnHandFireSpawner",40,0,0,5);
		Goto ReallyReady;

	ReadyBarrel:
		TNT1 A 0 A_JumpIf(CountInv("PowerStrength") == 0,"FireBarrel");
        TNT1 A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		MARN A 0 ACS_ExecuteAlways(294, 0, 0, 0, 0);//Makes player slower.
	//	THRG A 2 A_WeaponReady(WRF_NOFIRE);
        THRG A 2 A_WeaponReady;
		Goto ReallyReady;

	ReadyShotgunguyHEad:
        TNT1 A 0 A_JumpIfInventory("Kicking",1,"DoKick");
	//	PTG1 B 2 A_WeaponReady(WRF_NOFIRE);
        PTG1 B 2 A_WeaponReady;
		Goto ReallyReady;


    Deselect:
	TNT1 A 0 A_jumpifinventory("PowerStrength",1,"ReadyCont");
	TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"FireBarrel");
	TNT1 A 0 A_JumpIfInventory("ShotgunguyHead",1,"DesShotgunguyHeadFire");
	TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"LSFire");
	TNT1 A 0 A_TakeInventory("IsWeaponLong",1);
	TNT1 A 0 A_TakeInventory("IsWeaponShort",1);
	TNT1 A 0 A_TakeInventory("IsWeaponWide",1);
	TNT1 A 0 A_TakeInventory("IsWeaponBFG",1);
	TNT1 A 0 A_Takeinventory("HasCutingWeapon",1);
	TNT1 A 0 A_Takeinventory("HasPlasmaWeapon",1);
	TNT1 A 0 A_TakeInventory("TossGrenade", 1);
	TNT1 A 0 A_Takeinventory("FistsSelected",1);
	TNT1 A 0 A_Takeinventory("Zoomed",1);
	TNT1 A 0 A_Takeinventory("ADSmode",1);
    TNT1 A 0 A_ZoomFactor(1.0);
	TNT1 AAAAAAAAAAAAAAAAAA 0 A_Lower;
    //TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"KillLS");
		TNT1 A 1;
		Wait;

    KillLS:
        THEA E 8;
        TNT1 A 0 A_FireProjectile("LSOHK",40,0,0,5);
        TNT1 A 0 A_Takeinventory("LostSoulFatality",1);
        THEA F 8;
		THEA F 1 A_Lower;
		Wait;
	Select:
	TNT1 A 0 A_Giveinventory("FistsSelected",1);
	TNT1 A 0 A_Takeinventory("HasCutingWeapon",1);
	TNT1 A 0 A_Takeinventory("HasPlasmaWeapon",1);
	TNT1 A 0 A_Takeinventory("SawSelected",1);
	TNT1 A 0 A_Takeinventory("ShotgunSelected",1);
	TNT1 A 0 A_Takeinventory("SSGSelected",1);
	TNT1 A 0 A_Takeinventory("MinigunSelected",1);
	TNT1 A 0 A_Takeinventory("PlasmaGunSelected",1);
	TNT1 A 0 A_Takeinventory("RocketLauncherSelected",1);
    TNT1 A 0 A_Takeinventory("GrenadeLauncherSelected",1);
	TNT1 A 0 A_Takeinventory("BFGSelected",1);
	TNT1 A 0 A_Takeinventory("BFG10kSelected",1);
	TNT1 A 0 A_Takeinventory("RailGunSelected",1);
	TNT1 A 0 A_Takeinventory("SubMachineGunSelected",1);
	TNT1 A 0 A_Takeinventory("RevenantLauncherSelected",1);
	TNT1 A 0 A_Takeinventory("LostSoulSelected",1);
	TNT1 A 0 A_Takeinventory("FlameCannonSelected",1);
	TNT1 A 0 A_Takeinventory("HasBarrel",1);
	TNT1 A 0 A_TakeInventory("TossGrenade", 1);
	TNT1 A 0 A_Takeinventory("Zoomed",1);
	TNT1 A 0 A_Takeinventory("ADSmode",1);
	TNT1 A 0 A_TakeInventory("IsWeaponLong",1);
	TNT1 A 0 A_TakeInventory("IsWeaponShort",1);
	TNT1 A 0 A_TakeInventory("IsWeaponWide",1);
	TNT1 A 0 A_TakeInventory("IsWeaponBFG",1);
    TNT1 A 0 A_ZoomFactor(1.0);
        ////////////////// Check if player is performing a fatality\\\\;
		TNT1 A 0;
		TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"ReadySoul");
        ////////////////////;
		TNT1 A 0 A_Raise;
		TNT1 A 1 A_Raise;
		Wait;

	////////////////////////////////////////////// Quick Pistol Fire;
	QuickPistolFire:
		TNT1 A 0 A_JumpIfInventory("PistolAmmo",1,2);
        Goto PistolReload;
        TNT1 AAAA 0;
		TNT1 A 0 A_TakeInventory("QuickPunching",1);
		BRTS A 1 A_PlaySound("weapons/pistolup");
        BRTS BCDZ 1;
	QuickPistolFireCont:
	    TNT1 A 0 A_JumpIfInventory("PistolAmmo",1,2);
        Goto PistolReload;
        TNT1 AAAA 0;
		TNT1 A 0 A_TakeInventory("QuickPunching",1);
        TNT1 A 0 A_PlaySound("weapons/bdpistol", CHAN_WEAPON);
		TNT1 A 0 A_FireProjectile("YellowFlareSpawn",0,0,0,0);
		PISF D 1 BRIGHT A_FireBullets (3, 3, -1, 6, "HitPuff");
		TNT1 A 0 A_ZoomFactor(0.985);
		TNT1 A 0 A_AlertMonsters;
        RIFF A 0 A_FireProjectile("Tracer", random(-1,1), 0, -1, -12, 0, random(-1,1));
		RIFF A 0 A_FireProjectile("GunFireSmoke", 0, 0, 0, 0, 0, 0);
		TNT1 A 0 A_FireProjectile("ShakeYourAssMinor", 0, 0, 0, 0);
		TNT1 A 0 A_Takeinventory("PistolAmmo",1);
	//	TNT1 A 0 A_Takeinventory("HandgunAmmo",1);
		TNT1 A 0 A_FireProjectile("Mp40CaseSpawn", 0,0,-1,-2);
        PISF BBB 1;
		TNT1 A 0 A_ZoomFactor(0.995);
		PISF Y 1 A_WeaponReady(1);
		TNT1 A 0 A_ZoomFactor(1.0);
		PISF C 1 A_WeaponReady(1);
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		PISF C 7 A_WeaponReady(1);
	//	TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFire");
	//	TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFire");
		PISF A 0 A_Refire;
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		TNT1 A 0 A_JumpIfInventory("QuickPunching",1, "QuickPistolFireCont");
		BRTS ZDCBAYX 1;
		TNT1 A 0 A_Jump(256, 5);
        D3GS DCBA 1;
		TNT1 A 0;
		TNT1 A 1 A_Lower;
		Goto Ready;

	 PistolReload:
		TNT1 A 0 A_ZoomFactor(1.0);
		TNT1 A 0 A_TakeInventory("QuickPunching",1);
		TNT1 A 0 A_Takeinventory("Reloading",1);
		TNT1 A 0 A_Takeinventory("ADSmode",1);
		TNT1 A 0 A_Takeinventory("Zoomed",1);
		TNT1 A 0 A_JumpIfInventory("PistolAmmo",16,54);
        TNT1 A 0 A_JumpIfInventory("PistolBullets",1,3);
        Goto ReallyReady;
        TNT1 AAA 0;
		DEGG A 1 A_WeaponReady;
		TNT1 A 0 A_Takeinventory("Zoomed",1);
		TNT1 A 0 A_GiveInventory ("Pumping", 1);
		TNT1 A 0 A_Takeinventory("Reloading",1);


        PISR ZYWXA 1 ;//A_JumpIfInventory("HasUnloaded", 1, 2)
		TNT1 A 0 A_FireProjectile("EmptyClipMP40",5,0,8,-4);
		TNT1 AA 0;
		TNT1 A 0 A_PlaySound("PSRLOUT", 1);
        PISR BCDE 2;
	//	TNT1 A 0 A_PlaySound("PSRLIN", 2);
		PISR F 8;
		PISR GHIJ 2;
		TNT1 A 0 A_PlaySound("PSRLIN", 2);
		PISR KKLLLL 1;
		PISR MMNNOQP 1;

		TNT1 A 0 A_JumpIfInventory("PistolAmmo",1,"InsertBullets2");//30+1 effect
	//	TNT1 A 0 A_GiveInventory("RifleWasEmpty", 1);
	InsertBullets:
		TNT1 AAAA 0;
		TNT1 A 0 A_JumpIfInventory("PistolAmmo",15,15);
		TNT1 A 0 A_JumpIfInventory("PistolBullets",1,3);
		Goto Ready;
        TNT1 AAAAAA 0;
		TNT1 A 0 A_Giveinventory("PistolAmmo",1);
	//	TNT1 A 0 A_Giveinventory("HandgunAmmo",1);
		TNT1 A 0 A_Takeinventory("PistolBullets",1);
		Goto InsertBullets;

		TNT1 AAAAAAAAAA 0;
		TNT1 A 0 A_Takeinventory("Reloading",1);
        Goto Ready;
		TNT1 AAAA 0;
		TNT1 A 0 A_Takeinventory("Reloading",1);
        Goto Ready;

	InsertBullets2:
		TNT1 AAAA 0;
		TNT1 A 0 A_JumpIfInventory("PistolAmmo",16,15);
		TNT1 A 0 A_JumpIfInventory("PistolBullets",1,3);
		Goto Ready;
        TNT1 AAAAAA 0;
		TNT1 A 0 A_Giveinventory("PistolAmmo",1);
	//	TNT1 A 0 A_Giveinventory("HandgunAmmo",1);
		TNT1 A 0 A_Takeinventory("PistolBullets",1);
		Goto InsertBullets2;

		TNT1 AAAAAAAAAA 0;
		TNT1 A 0 A_Takeinventory("Reloading",1);
        Goto Ready;
		TNT1 AAAA 0;
		TNT1 A 0 A_Takeinventory("Reloading",1);
        Goto Ready;

	LoadChamber:
		DEGS ABCD 1;
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("IronSights", 0);
		DEGR H 1 A_PlaySound("PSRLFIN", 1);
		DEGR IJK 1;
		DEGR LMNO 1;
		DEGG A 1;
		TNT1 A 0 A_TakeInventory("QuickPunching",1);
		TNT1 A 0 A_Takeinventory("Reloading",1);
		TNT1 A 0 A_Takeinventory("RifleWasEmpty",1);
		DEGS DCBA 1;
		TNT1 A 0 A_Jump(256, 5);
        D3GS DCBA 1;
		TNT1 A 0;
		TNT1 A 1 A_Lower;
		Goto Ready;

	////////////////////////////////////////////// Normal Attacks;

	Fire:
		TNT1 A 0
		{
			if(countinv("FinisherToken",AAPTR_PLAYER_GETTARGET)>=1 && A_CheckLOF("Null",CLOFF_SETTARGET|CLOFF_NOAIM_VERT|CLOFF_IGNOREGHOST|CLOFF_MUSTBESOLID ,180))
			{ return ResolveState("PermormGloryKill");	}

			return ResolveState(Null);
		}
		TNT1 A 0 A_JumpIfInventory("ShotgunguyHead",1,"ShotgunguyHeadFire");
		TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"LSFireNot");
		TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"FireBarrel");
		TNT1 A 0 A_jumpifinventory("PowerStrength",1,"FatalityFire");
		TNT1 A 0 A_Jump(128, "PunchRight");

	PunchLeft:
		PUNG BCD 1;
	//	PUNG AHBJFCD 1;
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrikeNormal", 0, 0, 0, -9);

		PUNG E 2;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_GiveInventory("PSeq1", 1);
	//	PUNG DCFJBHA 2;
		PUNG DCB 2;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
        PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_Refire;
		Goto ReallyReady;

	 PunchRight:
	    TNT1 A 0;

	    PUP2 B 1;
		PUP2 C 1;
		PUN2 AC 1;
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrikeNormal", 0, 0, 0, -9);
		//PUN2 A 0 A_Custompunch(25,1,1,"MeleePuff");
		PUN2 DE 2;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_GiveInventory("PSeq2", 1);
		PUN2 FFGH 1;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
		PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_Refire;
		//TNT1 A 0 A_Refire;
		Goto ReallyReady;


	AltFire:
		TNT1 A 0;
		TNT1 A 0
		{
			if(countinv("FinisherToken",AAPTR_PLAYER_GETTARGET)>=1 && A_CheckLOF("Null",CLOFF_SETTARGET|CLOFF_NOAIM_VERT|CLOFF_IGNOREGHOST|CLOFF_MUSTBESOLID ,180))
			{ return ResolveState("PermormGloryKill");	}

			return ResolveState(Null);
		}
		TNT1 A 0 A_JumpIfInventory("ShotgunguyHead",1,"LSFireNot");
		TNT1 A 0 A_jumpifinventory("LostSoulFatality",1,"LSFire");
		TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"AltFireBarrel");
		TNT1 A 0 A_jumpifinventory("PowerStrength",1,"SuperAltFire");
		TNT1 A 0 A_JumpIfInventory("PSeq1", 1, "AltFireQUick");
		TNT1 A 0 A_JumpIfInventory("PSeq2", 1, "AltFire2");
		TNT1 A 0 SetPlayerProperty(0,1,0);
		TNT1 A 3;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		TNT1 A 8;
		TNT1 A 0 A_Recoil(-2);
		TNT1 A 0 A_Jump(256, "AltFireQuick", "AltFire2", "AltFire3");

	AltFireQuick:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN3 ABCDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN3 F 1;
		RIFF AA 0 A_FireProjectile("KickAttack", 0, 0, 0, -9);
		PUN3 GHI 1;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN3 JK 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;

	AltFire3:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN4 ABCDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN4 F 1;
		RIFF A 0 A_FireProjectile("KickAttack", 0, 0, 0, -9);
		PUN4 GHI 1;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN4 JK 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;

	AltFire2:
		TNT1 A 0;

		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN5 CDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN5 F 1;
		TNT1 A 0 A_GiveInventory("HeavyStrikeUpward", 1);
		RIFF A 0 A_FireProjectile("KickAttack", 0, 0, 0, 0);
		PUN5 GHIJ 1;
		TNT1 A 0 A_TakeInventory("HeavyStrikeUpward", 1);
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN5 KLM 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;


	/////////////////////////////////////////////// Fatalities;

	FatalityFire:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("NoFatality", 1, "PunchBerserkNoFatality");
		TNT1 A 0 A_Jump(128, "PunchRightFatality");

	PunchLeftFatality:
		PUNG BCD 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrike1Fatality", 0, 0, 0, -9);

		PUNG E 4;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_GiveInventory("PSeq1", 1);
		PUNG DCB 1;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
        PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_Refire;
		Goto ReallyReady;

	 PunchRightFatality:
	    TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"AltFireBarrel");

	    PUP2 B 1;
		PUP2 C 1;
		PUN2 AC 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrike1Fatality", 0, 0, 0, -9);
		//PUN2 A 0 A_Custompunch(25,1,1,"MeleePuff");
		PUN2 DD 2;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_GiveInventory("PSeq2", 1);
		PUN2 EFGH 1;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
		PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_Refire;
		//TNT1 A 0 A_Refire;
		Goto ReallyReady;


	SuperAltFire:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("PSeq1", 1, "AltFireQUickFatality");
		TNT1 A 0 A_JumpIfInventory("PSeq2", 1, "AltFire2Fatality");
		TNT1 A 4;
		TNT1 A 0 A_Recoil(-2);
		TNT1 A 0 A_Jump(256, "AltFireQuickFatality", "AltFire2Fatality", "AltFire3Fatality");

		AltFireQuickFatality:
		TNT1 A 4;
		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN3 ABCDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN3 F 1;

		TNT1 A 0 A_GiveInventory("HeavyStrikeLeft", 1);
		RIFF AAA 0 A_FireProjectile("SuperKickAttack", 0, 0, 0, -9);
		PUN3 GHI 1;
		TNT1 A 0 A_TakeInventory("HeavyStrikeLeft", 1);
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN3 JK 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;

	AltFire2Fatality:
		TNT1 A 4;

		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN5 CDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN5 F 1;

		TNT1 A 0 A_GiveInventory("HeavyStrikeUpward", 1);
		RIFF AAA 0 A_FireProjectile("SuperKickAttack", 0, 0, 0, 0);
		PUN5 GHIJ 1;
		TNT1 A 0 A_TakeInventory("HeavyStrikeUpward", 1);
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN5 KLM 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;

	AltFire3Fatality:
		TNT1 A 4;
		TNT1 A 0 A_TakeInventory("PSeq1", 2);
		TNT1 A 0 A_TakeInventory("PSeq2", 2);
		PUN4 ABCDE 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUN4 F 1;
		TNT1 A 0 A_GiveInventory("HeavyStrikerIGHT", 1);
		RIFF AAA 0 A_FireProjectile("SuperKickAttack", 0, 0, 0, -9);
		PUN4 GHI 1;
		TNT1 A 0 A_TakeInventory("HeavyStrikeRight", 1);
		TNT1 A 0 SetPlayerProperty(0,0,0);
		PUN4 JK 1 A_JumpIfInventory("Kicking",1,"KickRight");
        TNT1 AAA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		PUN5 BA 1 A_WeaponReady(1);
		TNT1 A 0 A_REfire;
		Goto ReallyReady;
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;

	KickRight:
		KIK2 ABC 1;
        TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 A_Giveinventory("Punching",1);
		TNT1 A 0 A_SetPitch(-6 + pitch);
		KIK2 D 1;
		PUN2 A 0 A_Custompunch(35,0,1,"MeleePuff");
		KIK2 DD 1;
		KIK2 ECBA 1;
		TNT1 A 5 A_TakeInventory("Kicking",1);
		Goto ReallyReady;


	KickLeft:
		KIK1 ABC 1;
        TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 A_Giveinventory("Punching",1);
		TNT1 A 0 A_SetPitch(-6 + pitch);
		KIK1 D 1;
		PUN2 A 0 A_Custompunch(35,0,1,"MeleePuff");
		KIK1 DD 1;
		KIK1 ECBA 1;
		TNT1 A 5 A_TakeInventory("Kicking",1);
		Goto ReallyReady;

	LSFireNot:
		TNT1 A 0;
		Goto ReadyCont;

	LSFire:
		THEF A 4;
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
        THEF B 4 A_FireProjectile("PoorLostSoul", 0, 1, 0, 0);
        THEF CD 4;
        TNT1 A 0 A_TakeInventory("LostSoulFatality",1);
		Goto ReallyReady;


	ShotgunguyHeadFire:
		PTG1 C 2 ;//A_WeaponReady(WRF_NOFIRE)
		PTG1 DEFGHIJ 1;
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
        PTG1 K 1 A_FireProjectile("SergeantHeadThrown", 0, 0, 0, 0);
        PTG1 LMNOP 1;
        TNT1 A 0 A_TakeInventory("ShotgunguyHead",1);
		Goto ReallyReady;

	DesShotgunguyHeadFire:
		PTG1 C 2;
		PTG1 DEFGHIJ 1;
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
        PTG1 K 1 A_FireProjectile("SergeantHeadThrown", 0, 0, 0, 0);
        PTG1 LMNOP 1;
        TNT1 A 0 A_TakeInventory("ShotgunguyHead",1);
		Goto ReallyReady;

	FireBarrel:
		THRF A 3 A_FireProjectile("ThrowedBarrel", 0, 1, 0, 0);
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		TNT1 A 0 A_TakeInventory("HasBarrel",1);
		MARN A 0 ACS_ExecuteAlways(295, 0, 0, 0, 0);//Makes player have normal speed.
        THRF ABCDEF 3;
		Goto ReallyReady;
	AltFireBarrel:
		PUNG A 1;
		THRF A 0 A_SpawnItemEx ("ExplosiveBarrel",40,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		MARN A 0 ACS_ExecuteAlways(295, 0, 0, 0, 0);//Makes player have normal speed.
        TNT1 A 0 A_PlaySound("skeleton/swing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		TNT1 A 0 A_TakeInventory("HasBarrel",1);
		PUNG A 5;
		Goto ReallyReady;


	PunchBerserkNoFatality:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "PunchRightBerserkNoFatality");

	PunchLeftBerserkNoFatality:
		PUNG BCD 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrike1Berserked", 0, 0, 0, -9);

		PUNG E 4;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_GiveInventory("PSeq1", 1);
		PUNG DCB 1;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
        PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickRight");
		TNT1 A 0 A_Refire;
		Goto ReallyReady;

	 PunchRightBerserkNoFatality:
	    TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("HasBarrel",1,"AltFireBarrel");

	    PUP2 B 1;
		PUP2 C 1;
		PUN2 AC 1;
        TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 A_Giveinventory("Punching",1);
		PUNG A 0 A_FireProjectile("MeleeStrike1Berserked", 0, 0, 0, -9);
		//PUN2 A 0 A_Custompunch(25,1,1,"MeleePuff");
		PUN2 DD 2;
		TNT1 A 0 A_TakeInventory("Kicking", 1);
		TNT1 A 0 A_GiveInventory("PSeq2", 1);
		PUN2 EFGH 1;
		TNT1 A 0 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		TNT1 A 0 A_JumpIfInventory("LostSoulFatality",1,"ReadySoul");
		PUNG AA 1 A_JumpIfInventory("Kicking",1,"KickLeft");
		TNT1 A 0 A_Refire;
		//TNT1 A 0 A_Refire;
		Goto ReallyReady;

		DoKick:
	    TNT1 A 0;
		TNT1 A 0
		{
			if(countinv("FinisherToken",AAPTR_PLAYER_GETTARGET)>=1 && A_CheckLOF("Null",CLOFF_SETTARGET|CLOFF_NOAIM_VERT|CLOFF_IGNOREGHOST|CLOFF_MUSTBESOLID ,180))
			{ return ResolveState("PermormGloryKill");	}

			return ResolveState(Null);
		}
		TNT1 A 0 A_Takeinventory("Zoomed",1);
        TNT1 A 0 A_ZoomFactor(1.0);
		TNT1 A 0 A_Takeinventory("ADSmode",1);
		NULL A 0 A_JumpIf (vel.z > 0, "AirKick");
		NULL A 0 A_JumpIf (vel.z < 0, "AirKick");
		NULL A 0 A_JumpIf (pitch > 32, "LowKickChecker1");
		Goto InitializeNormalKick;

		LowKickChecker1:
		TNT1 A 0;
	    NULL A 0 A_JumpIf (pitch > 90, "InitializeNormalKick");
		Goto LowKick;

		LowKick:
		TNT1 A 0 A_PlaySound("KICK");
		KICK UVW 1;
		KICK X 1;
		RIFF A 0 A_FireProjectile("KickAttackDetectDowned", 0, 0, 0, 0);
        KICK Y 1;
		KICK Z 4;
		KICK YX 1;
		KICK A 0 A_Takeinventory("Kicking",1);
		KICK WVU 1;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		Goto ReallyReady;

		InitializeNOrmalKick:
		TNT1 A 0;
		TNT1 A 0 A_Takeinventory("Zoomed",1);
        TNT1 A 0 A_ZoomFactor(1.0);
		TNT1 A 0 A_Takeinventory("ADSmode",1);
        TNT1 A 0 A_jumpifinventory("PowerStrength",1,"BerserkerKick");
		TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 SetPlayerProperty(0,1,0);
		KICK BCD 1;
		RIFF A 0 A_FireProjectile("KickAttack", 0, 0, 0, -7);
        KICK H 5;
		KICK A 0 A_Takeinventory("Kicking",1);
		KICK I 1;
		KICK GFEDCBA 1;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		Goto ReallyReady;
    BerserkerKick:
		TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 SetPlayerProperty(0,1,0);
		KICK BCD 1;
        RIFF A 0 A_FireProjectile("SuperKickAttack", 0, 0, 0, -7);
        KICK H 5;
		KICK A 0 A_Takeinventory("Kicking",1);
		KICK I 1;
		KICK GFEDCBA 1;
		TNT1 A 0 SetPlayerProperty(0,0,0);
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		Goto ReallyReady;

	AirKick:
	    TNT1 A 0 A_jumpifinventory("PowerStrength",1,"SuperAirKick");
		TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 A_Recoil (-6);
		KICK JKLMN 1;
        RIFF A 0 A_FireProjectile("AirKickAttack", 0, 0, 0, -31);
        KICK O 3;
		KICK A 0 A_Takeinventory("Kicking",1);
		KICK PQRST 2;
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		Goto ReallyReady;

	SuperAirKick:
		TNT1 A 0 A_PlaySound("KICK");
		TNT1 A 0 A_Recoil (-6);
		KICK JKLMN 1;
        RIFF A 0 A_FireProjectile("SuperAirKickAttack", 0, 0, 0, -31);
        KICK O 3;
		KICK A 0 A_Takeinventory("Kicking",1);
		KICK PQRST 2;
		TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
		Goto ReallyReady;
	}
}
